// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLWEmP03PSvyrUrOcGIgGa53UvxIsGleo',
    appId: '1:658816170887:web:e3229093798786dc56f122',
    messagingSenderId: '658816170887',
    projectId: 'b2retl-f0745',
    authDomain: 'b2retl-f0745.firebaseapp.com',
    storageBucket: 'b2retl-f0745.appspot.com',
    measurementId: 'G-CWEM9XZHT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZAyfGU8VqqifNDvSdNBEiebFN1RGJKPc',
    appId: '1:658816170887:android:406ea36c9da8617556f122',
    messagingSenderId: '658816170887',
    projectId: 'b2retl-f0745',
    storageBucket: 'b2retl-f0745.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC93zz0EazcfkUjoC4fPNaIo2WhzXHCrdw',
    appId: '1:658816170887:ios:01885a085d6126f656f122',
    messagingSenderId: '658816170887',
    projectId: 'b2retl-f0745',
    storageBucket: 'b2retl-f0745.appspot.com',
    iosClientId: '658816170887-c5rvnn6s65h234tgb3pr4n5ojsa2vjo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.b2retl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC93zz0EazcfkUjoC4fPNaIo2WhzXHCrdw',
    appId: '1:658816170887:ios:01885a085d6126f656f122',
    messagingSenderId: '658816170887',
    projectId: 'b2retl-f0745',
    storageBucket: 'b2retl-f0745.appspot.com',
    iosClientId: '658816170887-c5rvnn6s65h234tgb3pr4n5ojsa2vjo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.b2retl',
  );
}
